# Generated by Django 6.0.2 on 2026-03-03 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_user_role_user_profile_completed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='average_rating',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3),
        ),
        migrations.AddField(
            model_name='user',
            name='reviews_count',
            field=models.IntegerField(default=0),
        ),
    ]
