# Generated by Django 6.0.2 on 2026-04-14 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_average_rating_user_reviews_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='inn',
            field=models.CharField(blank=True, max_length=12),
        ),
        migrations.AddField(
            model_name='user',
            name='kpp',
            field=models.CharField(blank=True, max_length=9),
        ),
        migrations.AddField(
            model_name='user',
            name='ogrnip',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='user',
            name='passport_number',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
