# Generated by Django 6.0.2 on 2026-04-14 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_inn_user_kpp_user_ogrnip_user_passport_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='passport_series',
            field=models.CharField(blank=True, max_length=4),
        ),
        migrations.AlterField(
            model_name='user',
            name='passport_number',
            field=models.CharField(blank=True, max_length=6),
        ),
    ]
