version: '3.9'

services:

  web:
    build: .
    command: daphne -b 0.0.0.0 -p 8000 arenda_site.asgi:application
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    environment:
      - DJANGO_SETTINGS_MODULE=arenda_site.settings
      - DEBUG=1
      - PYTHONUNBUFFERED=1
      - EMAIL_HOST_USER=mokitoki.notifications@gmail.com
      - EMAIL_HOST_PASSWORD=smvc syis jbce xpwl

  db:
    image: postgres:15
    environment:
      POSTGRES_DB: arenda
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./Frontend:/usr/share/nginx/html 
    depends_on:
      - web

volumes:
  postgres_data: