# Generated by Django 6.0.2 on 2026-04-27 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0003_booking_paid_at_booking_payment_expires_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_number', models.CharField(editable=False, max_length=64, unique=True)),
                ('file', models.FileField(blank=True, upload_to='contracts/')),
                ('is_signed', models.BooleanField(default=False)),
                ('renter_signer_name', models.CharField(blank=True, max_length=255)),
                ('renter_signature_code', models.CharField(blank=True, max_length=128)),
                ('renter_signed_at', models.DateTimeField(blank=True, null=True)),
                ('owner_signer_name', models.CharField(blank=True, max_length=255)),
                ('owner_signature_code', models.CharField(blank=True, max_length=128)),
                ('owner_signed_at', models.DateTimeField(blank=True, null=True)),
                ('signed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='contract', to='bookings.booking')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
