# Generated by Django 6.0.2 on 2026-03-10 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0003_itemimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='average_rating',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3),
        ),
        migrations.AddField(
            model_name='item',
            name='reviews_count',
            field=models.IntegerField(default=0),
        ),
    ]
