# Generated by Django 6.0.2 on 2026-04-18 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0004_item_average_rating_item_reviews_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='delivery_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='item',
            name='deposit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='item',
            name='price_per_hour',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='rent_type',
            field=models.CharField(choices=[('hourly', 'Почасовая'), ('daily', 'Посуточная'), ('both', 'Почасовая и посуточная')], default='daily', max_length=10),
        ),
        migrations.AlterField(
            model_name='item',
            name='price_per_day',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
