# Generated by Django 6.0.2 on 2026-04-24 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0005_itemvideo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itemimage',
            options={'ordering': ['-uploaded_at']},
        ),
        migrations.AlterModelOptions(
            name='itemvideo',
            options={'ordering': ['-uploaded_at']},
        ),
    ]
