# Generated by Django 6.0.2 on 2026-04-27 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0007_itemreview'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='itemreview',
            new_name='items_itemr_item_id_fe3bc0_idx',
            old_name='items_itemr_item_id_3f6d3c_idx',
        ),
        migrations.RenameIndex(
            model_name='itemreview',
            new_name='items_itemr_author__748811_idx',
            old_name='items_itemr_author__a8b2a6_idx',
        ),
    ]
