# Generated by Django 6.0.2 on 2026-05-24 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0010_russian_moderation_choice_labels'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='deposit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Залог'),
        ),
    ]
