# Generated by Django 6.0.2 on 2026-05-23 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PostOffice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('postal_code', models.CharField(max_length=10, unique=True, verbose_name='Почтовый индекс')),
                ('address_str', models.CharField(max_length=500, verbose_name='Адрес')),
                ('region', models.CharField(blank=True, default='', max_length=200, verbose_name='Регион')),
                ('city', models.CharField(blank=True, default='', max_length=200, verbose_name='Город')),
                ('is_closed', models.BooleanField(default=False, verbose_name='Закрыто')),
                ('type_code', models.CharField(blank=True, default='', max_length=50, verbose_name='Тип отделения')),
                ('geo_lat', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='Широта')),
                ('geo_lon', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='Долгота')),
                ('schedule_mon', models.CharField(blank=True, default='', max_length=50)),
                ('schedule_tue', models.CharField(blank=True, default='', max_length=50)),
                ('schedule_wed', models.CharField(blank=True, default='', max_length=50)),
                ('schedule_thu', models.CharField(blank=True, default='', max_length=50)),
                ('schedule_fri', models.CharField(blank=True, default='', max_length=50)),
                ('schedule_sat', models.CharField(blank=True, default='', max_length=50)),
                ('schedule_sun', models.CharField(blank=True, default='', max_length=50)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Отделение Почты России',
                'verbose_name_plural': 'Отделения Почты России',
                'ordering': ['postal_code'],
                'indexes': [models.Index(fields=['city'], name='postoffices_city_21501a_idx'), models.Index(fields=['postal_code'], name='postoffices_postal__531751_idx')],
            },
        ),
    ]
