# Generated by Django 6.0.2 on 2026-04-24 18:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0001_initial'),
        ('items', '0006_alter_itemimage_options_alter_itemvideo_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chats', to='items.item'),
        ),
    ]
