# Generated by Django 6.0.2 on 2026-04-18 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='rent_type',
            field=models.CharField(choices=[('hourly', 'Почасовая'), ('daily', 'Посуточная')], default='daily', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='booking',
            name='end_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='booking',
            name='start_date',
            field=models.DateTimeField(),
        ),
    ]
