# Generated by Django 6.0.2 on 2026-05-23 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_review_is_hidden_review_moderated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='pickup_point',
            field=models.CharField(blank=True, default='', max_length=300, verbose_name='Место самовывоза'),
        ),
    ]
