# Generated by Django 6.0.2 on 2026-05-24 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0005_booking_pickup_point'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='deposit_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Сумма залога'),
        ),
        migrations.AddField(
            model_name='booking',
            name='deposit_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='deposit_paid_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='deposit_reference',
            field=models.UUIDField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='deposit_status',
            field=models.CharField(choices=[('not_required', 'Not required'), ('unpaid', 'Unpaid'), ('pending', 'Pending'), ('paid', 'Paid'), ('returned', 'Returned'), ('failed', 'Failed')], default='unpaid', max_length=20, verbose_name='Статус залога'),
        ),
    ]
