# Generated by Django 6.0.2 on 2026-05-24 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0006_booking_deposit_amount_booking_deposit_expires_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='owner_return_confirmed',
            field=models.BooleanField(default=False, verbose_name='Арендодатель подтвердил возврат'),
        ),
        migrations.AddField(
            model_name='booking',
            name='owner_return_confirmed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата подтверждения возврата арендодателем'),
        ),
        migrations.AddField(
            model_name='booking',
            name='owner_return_photo',
            field=models.ImageField(blank=True, null=True, upload_to='handover_photos/', verbose_name='Фото при возврате (арендодатель)'),
        ),
        migrations.AddField(
            model_name='booking',
            name='renter_cancel_reason',
            field=models.TextField(blank=True, default='', verbose_name='Причина отказа арендатора'),
        ),
        migrations.AddField(
            model_name='booking',
            name='renter_pickup_confirmed',
            field=models.BooleanField(default=False, verbose_name='Арендатор подтвердил получение'),
        ),
        migrations.AddField(
            model_name='booking',
            name='renter_pickup_confirmed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата подтверждения получения арендатором'),
        ),
        migrations.AddField(
            model_name='booking',
            name='renter_pickup_photo',
            field=models.ImageField(blank=True, null=True, upload_to='handover_photos/', verbose_name='Фото при получении (арендатор)'),
        ),
        migrations.AddField(
            model_name='booking',
            name='return_reason',
            field=models.TextField(blank=True, default='', verbose_name='Причина возврата'),
        ),
        migrations.AddField(
            model_name='booking',
            name='return_requested',
            field=models.BooleanField(default=False, verbose_name='Арендатор запросил возврат средств'),
        ),
        migrations.AddField(
            model_name='booking',
            name='return_requested_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата запроса возврата'),
        ),
        migrations.AddField(
            model_name='booking',
            name='return_status',
            field=models.CharField(choices=[('none', 'Нет'), ('requested', 'Запрошен'), ('approved', 'Одобрен'), ('rejected', 'Отклонён'), ('completed', 'Выполнен')], default='none', max_length=20, verbose_name='Статус СБП-возврата'),
        ),
    ]
