# Generated by Django 6.0.2 on 2026-05-24 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0007_booking_owner_return_confirmed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='platform_fee',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Сервисный сбор платформы (5%)'),
        ),
        migrations.AddField(
            model_name='booking',
            name='rent_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Сумма аренды (без залога и комиссии)'),
        ),
    ]
