# Generated by Django 6.0.2 on 2026-04-22 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('booking_created', 'Booking Created'), ('booking_confirmed', 'Booking Confirmed'), ('booking_cancelled', 'Booking Cancelled'), ('payment_confirmed', 'Payment Confirmed'), ('return_reminder', 'Return Reminder'), ('new_message', 'New Message'), ('new_review', 'New Review')], max_length=50),
        ),
    ]
