# Generated by Django 6.0.2 on 2026-04-24 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_alter_notification_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('booking_created', 'Новая заявка на аренду'), ('booking_confirmed', 'Бронирование подтверждено'), ('booking_cancelled', 'Бронирование отменено'), ('payment_confirmed', 'Оплата подтверждена'), ('return_reminder', 'Напоминание о возврате'), ('new_message', 'Новое сообщение'), ('new_review', 'Новый отзыв')], max_length=50),
        ),
    ]
