# Generated by Django 6.0.2 on 2026-05-21 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_notification_metadata_alter_notification_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('booking_created', 'Новая заявка на аренду'), ('booking_confirmed', 'Бронирование подтверждено'), ('booking_cancelled', 'Бронирование отменено'), ('payment_confirmed', 'Оплата подтверждена'), ('return_reminder', 'Напоминание о возврате'), ('new_message', 'Новое сообщение'), ('new_review', 'Новый отзыв'), ('item_moderation_request', 'Заявка на модерацию объявления'), ('item_moderation_approved', 'Объявление одобрено'), ('item_moderation_rejected', 'Объявление отклонено')], max_length=50),
        ),
    ]
